#helm:generate helm tpl -d tpl/values.toml --out $HELM_GENERATE_DIR/manifests/webapp-rc.yml $HELM_GENERATE_DIR/tpl/webapp-rc.yml
apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp-{{ .image.version }}
  labels:
    tier: frontend
    heritage: helm
spec:
  replicas: 2
  selector:
    tier: frontend
    version: {{ .image.version }}
  template:
    metadata:
      labels:
        tier: frontend
        heritage: helm 
        version: {{ .image.version }}
    spec:
      containers:
      - name: webapp-{{ .image.version }}
        imagePullPolicy: Always
        image: {{ .image.name }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
