apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    tier: webbackend
    heritage: helm
spec:
  type: ClusterIP
  #type: LoadBalancer
  ports:
  - name: dbport
    port: 5432
  selector:
    tier: webbackend
